# Generated by Django 4.1.5 on 2023-01-03 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='タイトル')),
                ('article', models.TextField(verbose_name='記事')),
                ('thumbnail', models.ImageField(null=True, upload_to='image/', verbose_name='サムネ用の写真')),
                ('short_description', models.CharField(max_length=100, null=True, verbose_name='軽い説明のテキスト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(verbose_name='更新日')),
                ('n_goods', models.ImageField(default=0, upload_to='', verbose_name='いいね')),
            ],
            options={
                'verbose_name': '投稿記事',
                'verbose_name_plural': '投稿記事',
                'db_table': 'book',
                'ordering': [],
            },
        ),
    ]
