# Generated by Django 4.1.5 on 2023-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="thumbnail",),
        migrations.AlterField(
            model_name="blogpost",
            name="n_goods",
            field=models.IntegerField(default=0, verbose_name="いいね"),
        ),
    ]
