# Generated by Django 4.1.5 on 2023-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0002_remove_blogpost_thumbnail_alter_blogpost_n_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail",
            field=models.ImageField(
                null=True, upload_to="images", verbose_name="サムネ用の写真"
            ),
        ),
    ]
