# Generated by Django 4.1.5 on 2023-01-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0003_blogpost_thumbnail"),
    ]

    operations = [
        migrations.AlterModelTable(name="blogpost", table="blogpost",),
    ]
