# Generated by Django 4.1.5 on 2023-01-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0004_alter_blogpost_table"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="thumbnail",),
    ]
